# Generated by Django 5.2.11 on 2026-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='article_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
