# Generated by Django 5.2.11 on 2026-02-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_content_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('hook', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expanded_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ideas', to='wizard.expandedkeyword')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ideas', to='wizard.project')),
            ],
        ),
        migrations.CreateModel(
            name='PinIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expanded_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_ideas', to='wizard.expandedkeyword')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_ideas', to='wizard.project')),
            ],
        ),
    ]
