# Generated by Django 5.2.11 on 2026-02-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_articleidea_pinidea'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('intro', models.TextField()),
                ('conclusion', models.TextField()),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail_prompt', models.TextField(blank=True)),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='blog_exports/')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='blog_exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('article_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='wizard.articleidea')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='wizard.project')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_prompt', models.TextField(blank=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='wizard.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
