# Generated by Django 5.2.11 on 2026-02-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_blogpost_blogsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='structured_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
