# Generated by Django 5.2.11 on 2026-02-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_blogpost_structured_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinidea',
            name='image_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pinidea',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pinidea',
            name='pinterest_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pinidea',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
