# Generated by Django 5.2.11 on 2026-02-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0006_pinidea_image_prompt_pinidea_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinidea',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pinidea',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
