# Generated by Django 5.2.11 on 2026-02-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0007_pinidea_scheduled_at_pinidea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
