# Generated by Django 5.2.11 on 2026-02-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0008_blogpost_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
