# Generated by Django 6.0.2 on 2026-02-16 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0009_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='docx_file',
        ),
    ]
