# Generated by Django 6.0.2 on 2026-02-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0010_remove_blogpost_docx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinidea',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='pins/custom/'),
        ),
        migrations.AddField(
            model_name='pinidea',
            name='image_source',
            field=models.CharField(choices=[('generated', 'AI Generated'), ('blog', 'Blog Image'), ('upload', 'Manual Upload')], default='generated', max_length=20),
        ),
    ]
