# Generated by Django 6.0.2 on 2026-02-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0011_pinidea_custom_image_pinidea_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinidea',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
