# Generated by Django 6.0.2 on 2026-02-17 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0012_alter_pinidea_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('info', 'Info')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Debug data or API responses')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wizard.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='media_assets/%Y/%m/%d/')),
                ('remote_url', models.URLField(blank=True, max_length=1024)),
                ('prompt', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('fal-ai', 'Fal AI'), ('together-ai', 'Together AI'), ('gemini', 'Gemini'), ('upload', 'Manual Upload'), ('external', 'External URL')], default='external', max_length=50)),
                ('is_vertical', models.BooleanField(default=True, help_text='True for Pins, False for Blogs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='wizard.project')),
            ],
        ),
        migrations.CreateModel(
            name='PinterestAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('auth_state', models.JSONField(default=dict, help_text='Stores Playwright storage state (cookies/localStorage)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinterest_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinterestBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='wizard.pinterestaccount')),
            ],
        ),
    ]
